---
title: Infrared light in the atmosphere
lab_date: '2021-02-08'
report_due_date: '2021-02-15'
lab_number: 3
github_classroom_assignment_url: https://classroom.github.com/a/p_q5Tals
pubdate: '2020-12-31'
date: '2021-02-08'
slug: lab_03
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
# Overview:

This lab will use the MODTRAN computer model to simulate the transmission of 
different wavelengths of infrared light through the atmosphere and explore the 
effect that different greenhouse gases have on infrared light and the earth's 
temperature.

There are two files for this lab.

1. Start by reading `lab-03-instructions.pdf`, which describes things you need
to know for this lab (about the R functions for working with the MODTRAN model
and the data that it produces, as well as some useful R functions that we will
use in procesing and graphing data for this lab.)

This file also has the exercises you will do for this lab.

2. When you come to lab, you will work through the exercises, and you will
edit the file `lab-03-exercises.Rmd` to write your answers and show your
work.

## Instructions:

* Accept this assignment.
* Clone a local copy of the file repository from github to your
  own computer.
* In your local repository, answer the exercises in the template
  `lab-03-exercises.Rmd`.
* When you are done, knit your `.Rmd` files into Word or PDF files.
* Use git to stage the files (including the `.Rmd` files
  and the new Word or PDF files) and commit the changes to your 
  local git repository.
* Push the changes from your local git repository to github.

  The last changes that you push before the due date will be graded.

I advise using git to commit changes frequently as you work and push those 
commits to github.

I also advise knitting your answers frequently to make sure that they 
knit correctly.

## Reading

**Before you come to lab**, please read the following document:

* [Instructions for Lab #3: Infrared Light](/lab_docs/lab_03_instructions){target="_blank"}

## Assignment
Accept the assignment at GitHub Classroom at <https://classroom.github.com/a/p_q5Tals>.
