---
title: Role-Playing Emissions Regulations
lab_date: '2020-04-06'
lab_number: 12
pubdate: '2019-12-31'
date: '2020-04-06'
slug: lab_12_assignment
fontsize: 12pt
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: yes
  pdf_document:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: yes
    includes:
      in_header: ees3310.sty
---
# Overview:

This week, we will do something very different. We will role-play different kinds of greenhouse gas emissions regulations: 

* "**Command-and-Control**," in which the EPA mandates the maximum emissions for each company, 
* "**Cap and Trade**," in which the EPA mandates the total emissions, and gives each company a certain number of permits, but the companies can buy and sell permits,
* "**Emissions Tax**," in which the EPA imposes a tax on each ton of emissions, and then reduces other taxes to keep the total government revenue constant.

Students will play different roles: some will act as government regulators at the Environmental Protection Agency and others will act as managers of different companies that must balance their desire to make money against the environmental damage from the pollution they emit.

There is no report to complete for this lab. 

Because of the disruptions to the semester from the COVID pandemic, this is purely an optional exercise. If you choose to do it, it will give you a hands-on sense of how the different policy approaches to regulating greenhouse gas emissions work. But if you already have too much to do and choose not to do this, there will be no penalty and the final exam _will not_ include any questions about this material.

## Reading

**Before you come to lab**, please read the following document:

* [Preparation for Lab on Regulating Greenhouse Gas Emissions](/lab_docs/lab_12_preparation){target="_blank"}

## Assignment

The GitHub Classroom assignment link has not been posted yet.
