---
title: Working with climate data
lab_date: '2020-01-13'
report_due_date: '2020-01-24'
lab_number: 2
github_classroom_assignment_url: https://classroom.github.com/a/pHx7-JvR
pubdate: '2019-12-31'
date: '2020-01-13'
slug: lab_02_assignment
output:
- blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: no
  pdf_document:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: no
    includes:
      in_header: ees3310.sty
---
# Overview:

This lab will introduce working with climate data using R and RMarkdown. 

There are two parts to this lab assignment: 

1. Part 1 is more like traditional homework. It consists of several exercises from chapter 3 of _Understanding the Forecast_, working with layer models of the greenhouse effect:
   * **All students** do Chapter 3, exercises 2--3.
   * **Graduate students** should also do Chapter 3, exercise 1.

     For the exercises, use the following numbers:

     * I~solar~ = 1350 W/m^2^
     * $\sigma = 5.67 \times 10^{-8}$
     * $\alpha = 0.30$
     * $\varepsilon = 1.0$

     For Part 1, you have a choice of either working it like traditional homework on paper or else doing it with RMarkdown, using an RMarkdown template in the repository for the assignment.
     If you do it in Rmarkdown, you will use the template file I provided and fill in the R code to do the calculations and then use RMarkdown to include the answers in the text of the document.

2. For part 2, you will practice using R to organize and analyze data on the climate. We will download temperature and CO~2~ measurements from scientific archives of climate data and practice producing tables of measurements, making plots of the measurements, and analyzing the series of measurements to determine the trends over time (rates of increase or decrease).

Both parts of the lab are due by the beginning of class on Friday, Jan. 24. If you do the layer model exercises on paper, turn in your work at the beginning of class. If you do the exercises with RMarkdown, knit your document to PDF or Word format and push it to GitHub. For Part 2, you must knit your work into a PDF or Word document and push the result to GitHub.

## Reminder:

**To turn in your RMarkdown homework you need to complete three steps:"**

1. Successfully **knit** `Lab_02_assignment_part_2.Rmd` into a `.pdf` or 
   Word (`.docx`) file. 
   
     If you choose to do Part 1 in RMarkdown instead 
     of on paper, also knit `Lab_02_assignment_part_1.Rmd`. Otherwise you will
     turn in Part 1 on paper at the beginning of class on Friday Jan. 24.
2. **Commit** your `.Rmd` (rmarkdown) document **and** the `.pdf` or `.docx` 
   file to your local git repository on your computer.
3. **Push** your local repository to GitHub, so Ms. Best and Prof. Gilligan 
   can see your final results.

**The last version of your work that you have pushed by the deadline is what will be graded.**
You will lose a lot of points if there is not a `.pdf` or `.docx` file with results.

As long as there is a file with results, we will be generous with partial credit.

## Reading

**Before you come to lab**, please read the following document:

* [Data Wrangling with R](/lab_docs/lab_02_overview){target="_blank"}

## Assignment

Accept the assignment at GitHub Classroom at <https://classroom.github.com/a/pHx7-JvR>.
