---
title: Convection and Clouds
lab_date: '2022-02-14'
report_due_date: '2022-02-21'
lab_number: 4
github_classroom_assignment_url: https://classroom.github.com/a/f3FG1c56
pubdate: '2021-12-31'
date: '2022-02-14'
slug: lab_04
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
# Overview:

This lab will explore the role of convection (the vertical motion of air) in the atmosphere, clouds, and their effects on climate.

Three things to note:

* Because of a mixup on my part, I inadvertently briefly made the answers 
  available, so to keep things fair for everyone, I have posted my answers for 
  everyone to see.
* Because of the in-class reading days on Feb. 23--24, I did not want to make 
  this lab due during or right before or after those reading days, so it will 
  be due Monday March 1. Lab 5 will also be due Mar 1., so you will have to get 
  them both in by then, but between the answers being available and the extra 
  week for this lab, I hope this will give you a lot more flexibility in getting 
  the assignments done.
* One big piece of this lab is to use RMarkdown to write a report that really 
  integrates text with code and graphics and tables that are generated by 
  RMarkdown. Use the fact that you can easily check your answers to the specific 
  questions to give you some freedom to think about how you want to present your 
  answers. Don't just copy and paste from my answers, but think about how you 
  would use RMarkdown to present your answers in your own way.

## Reading

**Before you come to lab**, please read the following document:

* [Instructions for Lab #4: Convection and Clouds](/lab_docs/lab_04_instructions){target="_blank"}

## Assignment
Accept the assignment at GitHub Classroom at <https://classroom.github.com/a/f3FG1c56>.
