---
title: Role-Playing Emissions Regulations
lab_date: '2022-04-18'
lab_number: 11
pubdate: '2021-12-31'
date: '2022-04-18'
slug: lab_11
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
---
# Overview:

This week, we will do something very different. We will role-play different kinds of greenhouse gas emissions regulations: 

* "**Command-and-Control**," in which the EPA mandates the maximum emissions for each company, 
* "**Cap and Trade**," in which the EPA mandates the total emissions, and gives each company a certain number of permits, but the companies can buy and sell permits,
* "**Emissions Tax**," in which the EPA imposes a tax on each ton of emissions, and then reduces other taxes to keep the total government revenue constant.

Students will play different roles: some will act as government regulators at the Environmental Protection Agency and others will act as managers of different companies that must balance their desire to make money against the environmental damage from the pollution they emit.

There is no report to complete for this lab.  Full credit will be given for showing up and participating in the lab exercise. For people who cannot come to lab, there will be a short homework assignment you can complete to get credit for this lab.

## Reading

**Before you come to lab**, please read the following document:

* [Preparation for Lab on Regulating Greenhouse Gas Emissions](/lab_docs/lab_11_preparation){target="_blank"}

## Assignment
This lab does not use GitHub Classroom.
