---
title: Geoengineering
class_date: '2022-04-18'
class_number: 36
weight: 36
slug: reading_36
pubdate: '2021-12-31'
date: '2022-04-18'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_36.pdf
---
## Reading:

### Required Reading (everyone):

* Handout: [L. Burns _et al._, _Solar Geoengineering_, Harvard Belfer Center Technology Factsheet (2019)](/files/reading_handouts/burns_2019_geoengineering_factsheet.pdf){target="_blank"}.
* Handout: [D.G. MacMartin, K.L. Ricke, &  D.W. Keith, "Solar geoengineering as part of an overall strategy for meeting the 1.5&deg;C Paris target," Phil. Trans. Roy. Soc A **376**, 2016054 (2018)](/files/reading_handouts/macmartin_2018_geoengineering_strategy.pdf){target="_blank"}.

### Required for Grad Students (optional for undergrads):

* Handout: [P.J. Irvine _et al._, "Towards a comprehensive climate impacts assessment of solar geoengineering," _Earth's Future_ **5**, 93--106 (2017)](/files/reading_handouts/irvine_2017_geoengineering_climate.pdf){target="_blank"}.

### Optional Extra Reading:

* The Climate Fix, 5.

### Reading Notes:

We will discuss geoengineering as an alternative to rapidly cutting greenhouse gas emissions. For today, we will focus on **solar radiation management**: Techniques for cancelling out the enhanced greenhouse effect by blocking sunlight from reaching the earth.

* As you read Pielke, pay attention to his discussion of the big picture. What does he mean by a **technological fix**, and what does he think about technological fixes for environmental problems?
* What are Daniel Sarewitz's criteria for successful technological fixes?
* In the context of technological fixes, Pielke describes climate change as a "wicked problem." This is a phrase with a specific meaning in public policy analysis. It comes from a 1973 paper,^[H.W.J. Rittel and M.M. Weber, "[Dilemmas in a General Theory of Planning](https://doi.org/10.1007/BF01405730)," Policy Sciences **4**, 155 (1973).] which defines "wicked problems" as possessing ten different properties, all of which make it very difficult, even impossible, to find satisfactory solutions. A few of these properties include: Wicked problems have high stakes, so it is unacceptable to choose a solution that proves ineffective. They are plagued by uncertainty, so no one can tell in advance whether a solution will work well. They invoilve important tradeoffs, so anything that makes a solution attractive to one constituency will make it unattractive to another. They are irreversible, so trial and error is not an effective approach for finding good solutions.

    As you read this chapter, think about how the problem of geoengineering the climate fits the criteria of a wicked problem.
* What does Pielke think about solar radiation management in terms of Sarewitz's criteria?
* Pielke begins this chapter by discussing geoengineering as a "**Plan B**" for climate policy. What does he mean by this?
* Where Pielke talks about "Plan B," Nordhaus describes geoengineering as "**salvage therapy**" for the planet. How does his account of solar radiation management compare to Pielke's? Where do the two agree and where do they disagree?
* Nordhaus, as an economist, focuses a lot on costs, comparing the costs and the benefits of any policy. How does he asses the costs and benefits of geoengineering?
* The short paper by Hegerl and Solomon presents solar radiation management geoengineering from the perspective of two top climate scientists. As you read their thoughts, which focus almost entirely on the scientific aspects, how do you think of this in comparison to the policy focus in Nordhaus's and Pielke's discussions?
