---
title: Climate Justice
class_date: '2022-04-11'
class_number: 33
weight: 33
slug: reading_33
pubdate: '2021-12-31'
date: '2022-04-11'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_33.pdf
---
## Reading:

### Required Reading (everyone):

* Handout: [F. Sultana, "Critical climate justice," _The Geographical Journal_ (2021)](/files/reading_handouts/sultana_2021_climate_justice.pdf){target="_blank"}.
* Handout: [A.R. Pearson _et al._, "Diverse segments of the US public underestimate the environmental concerns of minority and low-income Americans," _PNAS_ **115**, 12429--12434 (2018)](/files/reading_handouts/pearson_2018_concerns.pdf){target="_blank"}.

### Reading Notes:

These readings focus on climate justice: how how climate change affects different groups of people differently, and ways in which marginalized groups of people are particularly vulnerable to the impacts of climate change and are often excluded from discourse about how to respond to climate change.

This paper, by a prominent geographer, takes a broad international perspective about how climate change intersects with gender, and argues for the merits of a feminist perspective on climate change.

This paper investigates how many people misunderstand the way low-income and minoritized Americans think about climate change and environmetnal sustainability, and the way stereotypes and misunderstanding tend to exclude people of color and people in pooverty from political discussions about climate and sustainability.

This paper presents an overview of climate justice. Read the abstract for an overview. Then read the introduction to environmental justice on pp. 359--362 lightly (you can skim it quickly). Read the sections starting with  "From Environmental Justice to Climate Justice" on pp. 362--371 more carefully. Focus on getting a feeling for what the big concerns about climate justice are and what the three major conceptualizations are (academic theories, elite organizations' perspectives, and grassroots activist perspectives). The paper examines two aspects of climate change and applies the three perspectives to each: both the impacts of climate change on communities, and what can be done to adapt to climate change and reduce the impacts.
