---
title: Renewable Energy
class_date: '2022-04-13'
class_number: 34
weight: 34
slug: reading_34
pubdate: '2021-12-31'
date: '2022-04-13'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_34.pdf
---
## Reading:

### Required Reading (everyone):

* Handout: [Ren21, _Key Messages for Decision Makers: Takeaways from the Renewables 2021 Global Status Report_ (Ren21, 2021)](/files/reading_handouts/GSR2021_Key_Messages.pdf){target="_blank"}.

### Required for Grad Students (optional for undergrads):

* Handout: [Ren21, _Renewables 2021 Global Status Report_](/files/reading_handouts/GSR2021_Full_Report.pdf){target="_blank"}, Ch. 1.

### Reading Notes:

In the _Key Facts_, focus on the text on pp. 5--12. In the latter parts, after p. 12, most of the report is figures. Look carefully at the sections on transportation (16--17), electric power generation (18--19), and international comparisons on pp. 20-23. Read lightly the sections on technoloogies on pp. 24--30. There are short text summaries and figures that illustrate the progress that has been made for different technologies.

In the _Global Status Report_, Focus on pp. 29--37 and 42--45, and 48-55
