---
title: 'Instructions for Lab #3: Infrared Light'
author: Jonathan Gilligan
lab_number: 3
lab_date: '2021-02-08'
pubdate: '2020-12-31'
date: '2021-02-08'
pdf_url: /files/lab_docs/lab_03/lab_03_instructions.pdf
slug: lab_03_instructions
output.blogdown::html_page:
  md_extensions: +tex_math_single_backslash+compact_definition_lists
  toc: yes
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="instructions" class="section level1">
<h1>Instructions</h1>
<p>It would be good to print these instructions and bring them to lab on
Monday, or else to have the PDF with the instructions handy during lab.</p>
<p>For these exercises, I recommend that you work on them with the interactive
web-based MODTRAN models to get a feel for how the models apply to the
exercise.</p>
<p>Once you are clear what you are doing, you can use the R scripts and RMarkdown
to turn those insights into reproducible research.</p>
<div id="using-modtran-with-rmarkdown." class="section level2">
<h2>Using MODTRAN with RMarkdown.</h2>
<p>This RMarkdown document includes the line <code>source("_scripts/modtran.R")</code>,
which loads a script with the following functions:</p>
<ul>
<li><p><code>run_modtran()</code> allows you to automatically download a file
with the data from a MODTRAN run. You call it with the following arguments:</p>
<ul>
<li><p><code>filename</code> is an optional name for a file to save the data to.
If you don’t specify the <code>filename</code>, then <code>run_modtran</code> will not save the
model output to the disk.
I recommend giving it a meaningful name: for instance, a run with
550 ppm CO2 and 3.4 ppm methane might be called “<code>modtran_440_34.txt</code>”.
Make up your own file names, but think about how you will tell which is
which.
I also recommend that you save the files in the <code>_data</code> subdirectory to keep
your project nicely organized.</p></li>
<li><p><code>co2_ppm</code> is the amount of CO<sub>2</sub> in parts per million. The default is 400.</p></li>
<li><p><code>ch4_ppm</code> is the amount of methane in parts per million. The default is 1.7.</p></li>
<li><p><code>trop_o3_ppb</code> is the amount of ozone in the troposphere, in parts per billion.
The default is 28. You probably won’t change this unless you’re setting all
greenhouse gases to zero.</p></li>
<li><p><code>strat_o3_scale</code> is the amount of stratospheric ozone, relative
to the naturally occurring levels in the ozone layer.
You probably won’t change this unless you’re setting all
greenhouse gases to zero.</p></li>
<li><p><code>h2o_scale</code> is the amount of water vapor, relative to the naturally
occurring levels in the atmosphere.
You probably won’t change this unless you’re setting all
greenhouse gases to zero.</p></li>
<li><p><code>freon_scale</code> is the amount of freon chemicals (used for refrigerators
and air conditioners), relative to the current amounts.
You probably won’t change this unless you’re setting all
greenhouse gases to zero.</p></li>
<li><p><code>delta_t</code> is the temperature offset, in degrees C.
You adjust this to restore radiative equilibrium after you change the
amount of CO<sub>2</sub> or other greenhouse gases.</p></li>
<li><p><code>h2o_fixed</code> is what quantity to hold fixed for water vapor.
Possible values are “vapor pressure” (the default), and “relative humidity”</p></li>
<li><p><code>atmosphere</code> is the locality in the MODTRAN model.
Possible values are:</p>
<ul>
<li><code>"tropical"</code> (the default),</li>
<li><code>"midlatitude summer"</code>,</li>
<li><code>"midlatitude winter"</code>,</li>
<li><code>"subarctic summer"</code>,</li>
<li><code>"subarctic winter"</code>,</li>
<li>and <code>"standard"</code> for the 1976 U.S. standard atmosphere.</li>
</ul></li>
<li><p><code>clouds</code> is the specification of clouds and rain.
Possible values are</p>
<ul>
<li><code>"none"</code> (the default),</li>
<li><code>"cumulus"</code>,</li>
<li><code>"altostratus"</code>,</li>
<li><code>"stratus"</code>,</li>
<li><code>"stratocumulus"</code>,</li>
<li><code>"nimbostratus"</code>,</li>
<li><code>"drizzle"</code>,</li>
<li><code>"light rain"</code>,</li>
<li><code>"medium rain"</code>,</li>
<li><code>"heavy rain"</code>,</li>
<li><code>"extreme rain"</code>,</li>
<li><code>"standard cirrus"</code>,</li>
<li><code>"subvisual cirrus"</code>,</li>
<li>and <code>"NOAA cirrus"</code>.</li>
</ul>
<p><strong>Stratus clouds</strong> are flat, opaque, and low-altitude.
<strong>Altostratus clouds</strong> are flat and medium altitude.
<strong>Cirrus clouds</strong> are thin and high-altitude. They are hard to model,
so there are three different varieties.
<strong>Cumulus clouds</strong> are thick and stretch from low altitudes to medium altitudes.
<strong>Stratocumulus clouds</strong> are like thunder clouds. They are very tall and
reach from low altitudes to the top of the troposphere.
<strong>Nimbostratus clouds</strong> are low and thick, like stratus, but produce rain.</p></li>
<li><p><code>altitude_km</code> is the altitude, in kilometers above sea level, that you
put your virtual sensor in the model.
The default is 70 km, which is above almost all of the atmosphere.</p>
<p>For some exercises, you may experiment with putting the sensor somewhere
around 8 to 12 km, which is the top of the troposphere, below the stratospheric
ozone layer.</p>
<p>For other exercises, you might want to put it at 0 km (ground level),
and set it to look up instead of down, so you can see the IR radiation
coming down to the ground from the atmosphere instead of looking at the
IR radiation going out to space.</p></li>
<li><p><code>looking</code> is the direction the sensor is looking. The options are
“down” (the default) or “up”.</p></li>
</ul>
<p>Any arguments you don’t specify explicitly take on their default value.
Thus,
<code>run_modtran(file.path(data_dir, "modtran_experiment_1.txt"), co2_ppm = 800, delta_t = 1.0, h2o_fixed = "relative humidity")</code>
would run with all the default values, except for 800 ppm CO<sub>2</sub>,
a temperature offset of 1°C, and holding relative humidity fixed.</p>
<p>The function <strong>returns a list with 7 elements</strong>:</p>
<ul>
<li><code>spectrum</code> is a data tibble with the spectral information (wavelength <code>lambda</code>,
wavenumber <code>k</code>, outgoing IR intensity <code>tk</code>, and a number of other variables.)</li>
<li><code>profile</code> is the profile of the atmosphere: a tibble with seven columns:
<ul>
<li><code>Z</code> is the altitude in km,</li>
<li><code>P</code> is the atmospheric pressure, in millibars, and</li>
<li><code>T</code> is the temperature in Kelvin.</li>
<li><code>H2O</code> is the concentration of water vapor, in parts per million at each
altitude.</li>
<li><code>O3</code> is the concentration of ozone, in parts per million at each
altitude.</li>
<li><code>CO2</code> is the concentration of carbon dioxide, in parts per million at each
altitude.</li>
<li><code>CH4</code> is the concentration of methane, in parts per million at each
altitude.</li>
</ul></li>
<li><code>co2</code> is the atmospheric CO<sub>2</sub> concentration</li>
<li><code>ch4</code> is the atmospheric methane concentration</li>
<li><code>i_out</code> is the intensity of the outgoing IR radiation flux.</li>
<li><code>t_ground</code> is the ground temperature (in Kelvin) used in the model run.
(Remember that this is something you set when you run the model.
MODTRAN cannot calculate the way ground temperature changes when
you change greenhouse gases, clouds, or other characteristics of the
atmosphere.)</li>
<li><code>t_tropo</code> is the temperature at the tropopause (in Kelvin).</li>
<li><code>h_tropo</code> is the height of the tropopause (in km).</li>
<li><code>alt</code> is the altitude of the virtual sensor.</li>
<li><code>sensor_direction</code> is the direction of the virtual sensor (“up” or “down”).</li>
</ul>
<p>You can assign the output of <code>run_modtran()</code> to a variable like this:
<code>mod_data = run_modtran("my_modtran_file.txt", co2_ppm = 400)</code> and then
you can pass the value of <code>mod_data</code> to the <code>plot_modtran()</code> function, as
described below.</p></li>
<li><p><code>read_modtran(filename)</code> allows you to read in a MODTRAN output file
(saved to the disk by <code>run_modtran()</code>. It returns a list with the
same elements as <code>run_modtran()</code>.</p></li>
<li><p><code>plot_modtran</code> generates a plot of the radiative spectrum.
There are many arguments, and I won’t explain them all here, but
the important ones are:</p>
<ul>
<li><p><code>modtran_data</code> is the data that would be returned by the <code>run_modtran()</code>
function. If you want to plot</p></li>
<li><p><code>filename</code> is the MODTRAN output file with the data to use for the plot.</p>
<p>You can also provide data directly to <code>plot_modtran</code> instead of reading
in a file:
Instead of writing
<code>plot_modtran("my_modtran_file.txt", ...)</code>,
you could write,
<code>plot_modtran(modtran_data = mod_data, ...)</code>,
where <code>mod_data</code> is the output of <code>run_modtran()</code> or <code>read_modtran()</code>.</p></li>
<li><p><code>descr</code> is an optional string to use for the title of the plot.
If you don’t specify anything, the function will make a title
that indicates the CO2 concentration and the altitude of the virtual
sensor.</p></li>
<li><p><code>i_out_ref</code> is a reference value for the outgoing infrared. If you don’t
specify it, it’s ignored, but if you specify it, then the plotting
function adds an annotation to indicate the difference in outgoing IR
between the current run being plotted and the reference value.
Typically, you’d run a baseline run of MODTRAN with default parameters
and then use the upward IR flux from that run as <code>i_out_ref</code> when you
change the CO<sub>2</sub> concentration or other model parameters.</p></li>
<li><p><code>delta_t</code> is the temperature offset for this model run. If you specify it,
the plotting function adds an annotation to indicate it.</p></li>
<li><p><code>text_size</code> allows you to adjust the size of the text used for axis labels
and the plot title.</p></li>
</ul></li>
</ul>
<div id="converting-temperature-units" class="section level3">
<h3>Converting temperature units</h3>
<ul>
<li><p>Some handy functions for converting temperature measurements
from one unit of measurement to another are:</p>
<ul>
<li><p><code>ktof(T)</code> converts <code>T</code> from Kelvin to Fahrenheit.</p></li>
<li><p><code>ktoc(T)</code> converts <code>T</code> from Kelvin to Celsius.</p></li>
<li><p><code>ftok(T)</code> converts <code>T</code> from Fahrenheit to Kelvin.</p></li>
<li><p><code>ctok(T)</code> converts <code>T</code> from Celsius to Kelvin.</p></li>
<li><p><code>ctof(T)</code> converts <code>T</code> from Celsius to Fahrenheit.</p></li>
<li><p><code>ftoc(T)</code> converts <code>T</code> from Fahrenheit to Celsius.</p></li>
</ul></li>
</ul>
<p>But be aware that if you want to convert the <em>difference between two
temperatures</em>, you need to convert the temperatures and then take the
difference:</p>
<pre class="r"><code>t1_k = 254 # Kelvin temperature
t2_k = 288 # Kelvin temperature
delta_t_k = t2_k - t1_k # Difference in temeprature, in Kelvin

delta_t_k</code></pre>
<pre><code>## [1] 34</code></pre>
<pre class="r"><code>t1_f = ktof(t1_k) # Fahrenheit temperatures
t2_f = ktof(t2_k)

t1_f</code></pre>
<pre><code>## [1] -2.47</code></pre>
<pre class="r"><code>t2_f</code></pre>
<pre><code>## [1] 58.73</code></pre>
<pre class="r"><code>delta_t_f = t2_f - t1_f # Difference in temperature, in Fahrenheit

delta_t_f</code></pre>
<pre><code>## [1] 61.2</code></pre>
<pre class="r"><code># This will give the wrong answer for the 
# temperature difference in Fahrenheit!
ktof(delta_t_k)</code></pre>
<pre><code>## [1] -398.47</code></pre>
<p>You see that 58.73 minus -2.47 is not -398.47.</p>
<ul>
<li><p>Some variables that I have defined for you are:</p>
<ul>
<li><p><code>sigma_sb</code> is the Stefan-Boltzmann constant.</p></li>
<li><p><code>solar_constant</code> is the Solar Constant (the intensity of sunlight at the
top of the atmosphere, 1350.).</p></li>
</ul></li>
</ul>
</div>
</div>
<div id="examples" class="section level2">
<h2>Examples:</h2>
<pre class="r"><code>modtran_baseline = run_modtran(filename = 
                                 file.path(data_dir, &quot;modtran_baseline.txt&quot;))</code></pre>
<p>You could also write this as</p>
<pre class="r"><code>run_modtran(filename = file.path(data_dir, &quot;modtran_baseline.txt&quot;))
modtran_baseline = read_modtran(file.path(data_dir, &quot;modtran_baseline.txt&quot;))</code></pre>
<p>Now you can extract the various values from modtran_baseline:</p>
<pre class="r"><code>baseline_i_out &lt;- modtran_baseline$i_out
baseline_t_trop &lt;- modtran_baseline$t_trop</code></pre>
<p>The baseline MODTRAN run has
<span class="math inline">\(I_{\text{out}} = 299.\)</span>
and
<span class="math inline">\(T_{\text{tropopause}} = 190.\)</span>.</p>
<pre class="r"><code>plot_modtran(modtran_baseline)</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/plot_modtran_baseline-1.png" width="672" /></p>
<p>Or you could write</p>
<pre class="r"><code>plot_modtran(filename = file.path(data_dir, &quot;modtran_baseline.txt&quot;))</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/plot_modtran_baseline_2-1.png" width="672" /></p>
<pre class="r"><code>double_co2 = run_modtran(filename = file.path(data_dir, &quot;modtran_double_co2.txt&quot;), 
            co2_ppm = 800)
plot_modtran(double_co2, i_out_ref = baseline_i_out, delta_t = 0)</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/double_co2-1.png" width="672" /></p>
<pre class="r"><code>mod_file = file.path(data_dir, &quot;modtran_double_co2_warming.txt&quot;)
double_co2_warming = run_modtran(filename = mod_file, 
                                 co2_ppm = 800, delta_t = 0.76)
plot_modtran(double_co2_warming, i_out_ref = baseline_i_out, delta_t = 0.76)</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/double_co2_warming-1.png" width="672" /></p>
</div>
</div>
<div id="a-few-new-r-functions-that-we-will-use-in-this-lab" class="section level1">
<h1>A few new R functions that we will use in this lab:</h1>
<div id="iterating-over-a-series" class="section level2">
<h2>Iterating over a series</h2>
<p>Sometimes you want to repeat something in R, executing the same commands for
many different values of a variable. We can do this with the <code>for</code> command:</p>
<pre class="r"><code>df = tibble(x = 1:10)

for (i in 1:4) {
  p = ggplot(df, aes(x = x, y = x^i)) + 
    geom_point() + geom_line() +
    labs(x = &quot;x&quot;, y = str_c(&quot;x to the power &quot;, i))
  plot(p)
}</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/loop-1.png" width="288" /><img src="/lab_docs/lab_03_instructions_files/figure-html/loop-2.png" width="288" /><img src="/lab_docs/lab_03_instructions_files/figure-html/loop-3.png" width="288" /><img src="/lab_docs/lab_03_instructions_files/figure-html/loop-4.png" width="288" /></p>
<p>This gives us a nice way to run MODTRAN over and over, with many different
values for the CO<sub>2</sub> concentration and recording the value of I<sub>out</sub> for each
concentration.</p>
<p>In the loop below, we set all the greenhouse gases to zero and then vary CO<sub>2</sub>.
We use a trick in R by making an empty tibble before we start the loop and then
for each iteration of the loop, we use <code>bind_rows</code> to append a row with the
data from that loop iteration.</p>
<pre class="r"><code>co2_values = c(0, 200, 400, 600, 800, 1000, 1200)
tbl = tibble()
for (co2 in co2_values) {
  filename = str_c(&quot;modtran_co2_&quot;, co2, &quot;.txt&quot;)
  mod_data = run_modtran(filename, co2_ppm = co2, ch4_ppm = 0, trop_o3_ppb = 0,
                         strat_o3_scale = 0, h2o_scale = 0, freon_scale = 0,
                         atmosphere = &quot;standard&quot;, altitude_km = 70)
  tbl = bind_rows(tbl, tibble(co2_ppm = co2, i_out = mod_data$i_out))
}

# The digits argument below sets the number of decimal places
# for each column in the table.
kable(tbl, digits = c(co2_ppm = 0, i_out = 1))</code></pre>
<p>This code runs <code>run_modtran</code> for each value of CO<sub>2</sub> in <code>co2_values</code>
and saves the result to a file <code>modtran_0.txt</code>, <code>modtran_200.txt</code>, and so
forth. I make the filenames from the values of <code>co2</code> using the <code>str_c</code> function,
which I explain below.</p>
</div>
<div id="manipulating-text-in-r" class="section level2">
<h2>Manipulating text in R</h2>
<p>R has many functions for manipulating text. When R stores text, it stores it
in character variables (these are also sometimes called “strings” because
text is like a string of characters).
For instance, we might want to make a label or a filename by combining several
variables.
We can use the function <code>str_c</code>, from the <code>tidyverse</code>:</p>
<pre class="r"><code>print(str_c(&quot;infra&quot;, &quot;red&quot;))</code></pre>
<pre><code>## [1] &quot;infrared&quot;</code></pre>
<pre class="r"><code>print(str_c(&quot;infra&quot;, &quot;red&quot;, sep = &quot;-&quot;))</code></pre>
<pre><code>## [1] &quot;infra-red&quot;</code></pre>
<pre class="r"><code>print(str_c(10, &quot;km&quot;, sep = &quot; &quot;))</code></pre>
<pre><code>## [1] &quot;10 km&quot;</code></pre>
<pre class="r"><code>print(str_c(&quot;one&quot;, &quot;two&quot;, &quot;three&quot;, &quot;four&quot;, sep = &quot;, &quot;))</code></pre>
<pre><code>## [1] &quot;one, two, three, four&quot;</code></pre>
<pre class="r"><code>x = 50

print(str_c(x, &quot;Watts&quot;))</code></pre>
<pre><code>## [1] &quot;50Watts&quot;</code></pre>
<pre class="r"><code>print(str_c(x, &quot; Watts&quot;))</code></pre>
<pre><code>## [1] &quot;50 Watts&quot;</code></pre>
<pre class="r"><code>print(str_c(x, &quot;Watts&quot;, sep = &quot; &quot;))</code></pre>
<pre><code>## [1] &quot;50 Watts&quot;</code></pre>
<p>Notice how <code>str_c</code> pastes the text together without any spaces between the
parts unless you tell it to use a separator (<code>sep</code>) between them.</p>
</div>
<div id="calculating-with-leads-and-lags" class="section level2">
<h2>Calculating with leads and lags</h2>
<p>Sometimes, when we are using <code>mutate</code> with a data tibble, we might want to
look at differences between a row and the row before or after it in the
tibble. We can do this with the <code>lead</code> and <code>lag</code> functions:</p>
<p>In the example below, the column <code>u</code> gets the value of the current row of
<code>y</code> minus the previous row of <code>y</code>, and the column <code>v</code> gets the value of the
next row of <code>y</code> minus the current row of <code>y</code>. Note that where there isn’t a
previous row, <code>lag</code> returns <code>NA</code> (missing value), and similarly for <code>lead</code>
when there isn’t a next row.</p>
<pre class="r"><code>tbl = tibble(x = 0:5, y = x^2)

tbl = tbl %&gt;% mutate(&quot;lag y&quot; = lag(y), &quot;lead y&quot; = lead(y), u = y - lag(y), 
                     v = lead(y) - y)
kable(tbl)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">x</th>
<th align="right">y</th>
<th align="right">lag y</th>
<th align="right">lead y</th>
<th align="right">u</th>
<th align="right">v</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">1</td>
<td align="right">NA</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">3</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">9</td>
<td align="right">4</td>
<td align="right">16</td>
<td align="right">5</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="right">16</td>
<td align="right">9</td>
<td align="right">25</td>
<td align="right">7</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">25</td>
<td align="right">16</td>
<td align="right">NA</td>
<td align="right">9</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>If you want to lead or lag by more than one row, you can just say, <code>lag(y, 5)</code>
to get the value of <code>y</code> 5 rows before the current one.</p>
<pre class="r"><code>tbl = tibble(x = 1:10)
tbl = tbl %&gt;% mutate(before = lag(x), after = lead(x), 
                     before.2 = lag(x, 2), after.3 = lead(x, 3))
kable(tbl)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">x</th>
<th align="right">before</th>
<th align="right">after</th>
<th align="right">before.2</th>
<th align="right">after.3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">NA</td>
<td align="right">2</td>
<td align="right">NA</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">NA</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">2</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">5</td>
<td align="right">7</td>
<td align="right">4</td>
<td align="right">9</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">6</td>
<td align="right">8</td>
<td align="right">5</td>
<td align="right">10</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">7</td>
<td align="right">9</td>
<td align="right">6</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">8</td>
<td align="right">10</td>
<td align="right">7</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">9</td>
<td align="right">NA</td>
<td align="right">8</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="modifying-x-and-y-axes-in-ggplot" class="section level2">
<h2>Modifying <em>x</em> and <em>y</em> axes in <code>ggplot</code></h2>
<p>It is easy to modify the <em>x</em> or <em>y</em> axis in <code>ggplot</code>. For instance, if
you want to put specific limits on the axis, or change where the labels
go, you can use <code>scale_x_continuous</code> or <code>scale_y_continuous</code>:</p>
<pre class="r"><code>tbl = tibble(x = 1:200, y = (x / 100)^5)

ggplot(tbl, aes(x = x, y = y)) + geom_line()</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/simple_plot-1.png" width="384" /></p>
<pre class="r"><code>ggplot(tbl, aes(x = x, y = y)) + geom_line() +
  scale_x_continuous(limits = c(0,150), breaks = seq(0, 150, 25)) +
  scale_y_continuous(limits = c(0,10))</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/scale_x-1.png" width="384" /></p>
<pre class="r"><code>tbl = tibble(x = 1:200, y = 5 - 2 * x + 3 * x^2)

# Note that in R when we are typing numbers, we can express scientific notation 
# as 1E6 for 1,000,000 2.67E-3 for 0.00267

ggplot(tbl, aes(x = x, y = y)) + geom_line() +
  scale_x_log10(limits = c(1,1000)) +
  scale_y_log10(limits = c(1,1E6))</code></pre>
<p><img src="/lab_docs/lab_03_instructions_files/figure-html/log_plot-1.png" width="384" /></p>
</div>
</div>
<div id="exercises-for-lab-3" class="section level1">
<h1>Exercises for Lab #3</h1>
<p>You should accept the GitHub Classroom assignment for Lab #3, create a new
RStudio project for the lab, choosing Version Control and the link to the
GitHub repository for your Lab 3 project, and then open the file
<code>lab-03-exercises.Rmd</code> in RStudio to do these exercises.</p>
</div>
<div id="chapter-4-exercises" class="section level1">
<h1>Chapter 4 Exercises</h1>
<div id="exercise-4.1-methane" class="section level2">
<h2>Exercise 4.1: Methane</h2>
<p>Methane has a current concentration of 1.7 ppm in the atmosphere and
is doubling at a faster rate than CO<sub>2</sub>.</p>
<ol style="list-style-type: lower-alpha">
<li><p><strong>Would an additional 10 ppm of methane in the atmosphere have a larger or
smaller impact on the outgoing IR flux than an additional 10 ppm of CO<sub>2</sub>
at current concentrations?</strong></p>
<p><strong>Suggestion:</strong></p>
<ul>
<li>Run MODTRAN in the default configuration (400 ppm CO<sub>2</sub> and 1.7 ppm
methane)</li>
<li>Run MODTRAN with an extra 10 ppm of CO<sub>2</sub> and the normal amount of methane.</li>
<li>Run MODTRAN with the normal amount of CO<sub>2</sub> and an extra 10 ppm of methane.</li>
</ul>
<p>What would you look at from the three runs to figure out whether 10 ppm of
methane or 10 ppm of CO<sub>2</sub> had the greater effect?</p></li>
<li><p><strong>Where in the spectrum does methane absorb? What concentration does it take
to begin to saturate the absorption in this band? Explain what you are looking
at to judge when the gas is saturated.</strong></p>
<p><strong>Hints</strong>:<br />
I recommend setting all the greenhouse gases to zero, and run MODTRAN.
Then run MODTRAN for several values of methane, starting at 1 ppm and
doubling the concentration until you get to around 128 ppm.
You can do this using a <code>for</code> loop, following the examples from the
lab instructions.</p>
<p>To set all the greenhouse gases to zero, you would call
<code>run_modtran(co2_ppm = 0, ch4_ppm = 0, trop_o3_ppb = 0, strat_o3_scale = 0, h2o_scale = 0, freon_scale = 0)</code></p>
<p>The spectrum of methane is complicated so it doesn’t saturate all at once.
Use <code>plot_modtran</code> to plot the spectrum for each concentration and describe
what you see and where you think methane begins to saturate and why.</p>
<p>By default, <code>plot_modtran</code> gives a plot a title that indicates the CO<sub>2</sub>
concentration. Here, CO<sub>2</sub> doesn’t change and we’re interested in the CH<sub>4</sub>
concentration, so you can use the <code>descr</code> argument to <code>plot_modtran</code> to
give the plots different titles. See the example below.</p>
<p>Remember that if you want to make several plots using a <code>for</code> loop, you need to
assign the result from <code>plot_modtran</code> or <code>ggplot</code> to a variable and then
use the <code>plot</code> or <code>print</code> function.</p>
<pre class="r"><code>for (ch4 in ch4_list) {
  mod_data = run_modtran(co2_ppm = 0, ch4_ppm = ch4, trop_o3_ppb = 0,
  strat_o3_scale = 0, h2o_scale = 0, freon_scale = 0)
  p = plot_modtran(mod_data)
  plot(p) # you could also say print(p) here.
}</code></pre></li>
<li><p><strong>Would a doubling of methane have as great an impact on the heat balance as a
doubling of CO<sub>2</sub>?</strong></p>
<p><strong>Suggestion:</strong></p>
<ul>
<li>Run MODTRAN in its default configuration (400 ppm CO<sub>2</sub> and 1.7 ppm methane)</li>
<li>Run it again with double the methane concentration.</li>
<li>Run it again with the default methane (1.7 ppm) but double the CO<sub>2</sub>
concentration.</li>
<li>Compare <span class="math inline">\(I_{\text{out}}\)</span> for the three runs.</li>
</ul></li>
<li><p><strong>What is the “equivalent CO<sub>2</sub>” of doubling atmospheric methane? That is to
say, how many ppm of CO<sub>2</sub> would lead to the same change in outgoing IR
radiation energy flux as doubling methane? What is the ratio of ppm CO<sub>2</sub>
change to ppm methane change?</strong></p></li>
</ol>
</div>
<div id="exercise-4.2-co2-graduate-students-only" class="section level2">
<h2>Exercise 4.2: CO<sub>2</sub> (Graduate students only)</h2>
<ol style="list-style-type: lower-alpha">
<li><p><strong>Is the direct effect of increasing CO<sub>2</sub> on the energy output at the top of
the atmosphere larger in high latitudes or in the tropics?</strong></p>
<p><strong>Hint:</strong>
Run MODTRAN with the atmosphere set to <code>tropical</code>, <code>midlatitude summer</code>,
and <code>subarctic summer</code>, and for each atmosphere, at 400 ppm and 800 ppm CO<sub>2</sub>.
For each atmosphere, calculate the difference between I<sub>out</sub> at 400 and 800
ppm CO<sub>2</sub> and determine how the effect of doubling CO<sub>2</sub> varies as you go
from tropical latitudes to subarctic ones.</p></li>
<li><p><strong>Set pCO<sub>2</sub> to an absurdly high value of 10,000 ppm. You will see a spike
in the CO<sub>2</sub> absorption band. What temperature is this light coming from?
Where in the atmosphere do you think this comes from?</strong></p>
<p><strong>Now turn on clouds and run the model again. Explain what you see.
Why are night-time temperatures warmer when there are clouds?</strong></p>
<p><strong>Hint:</strong> MODTRAN simulates the upward directed, outgoing longwave radiation
as seen by a sensor looking down from some height.
For the first part of this exercise, start with the sensor at its
default altitude of 70 km (you set this with the <code>altitude_km</code> argument to
<code>run_modtran</code>), and successively lower it by 10 km at a time until
you get to 10 km.
What happens to the spike as you lower the sensor? What does this say about
what part of the atmosphere is responsible for the spike in the middle of the
CO<sub>2</sub> absorption at very high values of CO<sub>2</sub>?</p>
<p>For the second part of this exercise, try using “altostratus” clouds.</p></li>
</ol>
</div>
<div id="exercise-4.3-water-vapor" class="section level2">
<h2>Exercise 4.3: Water vapor</h2>
<p>Our theory of climate presumes that an increase in the temperature at ground
level will lead to an increase in the outgoing IR energy flux at the top of the
atmosphere.</p>
<ol style="list-style-type: lower-alpha">
<li><p>How much extra outgoing IR would you get by raising the temperature of the
ground by 5°C? What effect does the ground temperature have on the
shape of the outgoing IR spectrum and why?**</p>
<p><strong>HINT</strong>: You can raise the temperature of the ground with the <code>delta_t</code>
artument to MODTRAN.</p></li>
<li><p><strong>More water can evaporate into warm air than into cool air. Change the
model settings to hold the water vapor at constant relative humidity
rather than constant vapor pressure (the default), calculate the change
in outgoing IR energy flux for a 5°C temperature increase.
Is it higher or lower? Does water vapor make the Earth more sensitive to
CO<sub>2</sub> increases or less sensitive?</strong></p>
<p><strong>Note:</strong> By default, the MODTRAM model holds water vapor pressure constant,
but you can set it to hold relative humidity constant instead with the
option <code>h2o_fixed = "relative humidity"</code>, like this:
<code>run_modtran(file_name, delta_t = 5, h2o_fixed = "relative humidity")</code>.</p></li>
<li><p><strong>Now see this effect in another way.</strong></p>
<ul>
<li><p><strong>Starting from the default base case, record the total outgoing
IR flux.</strong></p></li>
<li><p><strong>Now double CO<sub>2</sub>. The temperature in the model stays the
same (that’s how the model is written), but the outgoing IR flux
goes down.</strong></p></li>
<li><p><strong>Using constant water vapor pressure, adjust the temperature offset
until you get the original IR flux back again. Record the change in
temperature.</strong></p></li>
<li><p><strong>Now repeat the exercise, but holding the relative humidity fixed
instead of the water vapor pressure.</strong></p></li>
<li><p><strong>The ratio of the warming when you hold relative humidity fixed
to the warming when you hold water vapor pressure fixed is the
feedback factor for water vapor. What is it?</strong></p></li>
</ul></li>
</ol>
</div>
</div>
<div id="chapter-5-exercise" class="section level1">
<h1>Chapter 5 Exercise</h1>
<div id="exercise-5.2-skin-height" class="section level2">
<h2>Exercise 5.2: Skin Height</h2>
<ol style="list-style-type: lower-alpha">
<li><p><strong>Run the MODTRAN model using the “tropical” atmosphere, without clouds,
and with the present-day CO<sub>2</sub> concentration (400 ppm).
Use the ground temperature reported
by the model to calculate
<span class="math inline">\(\varepsilon \sigma T_{\text{ground}}^4\)</span>,
the heat flux emitted by the ground.
Assume <span class="math inline">\(\varepsilon = 1\)</span>, and I have already provided the value of the
Stefan-Boltzmann constant <span class="math inline">\(\sigma\)</span>, as the R variable <code>sigma_sb</code>,
which equals 5.670×10<sup>-8</sup>.
(I defined it in the script “utils.R”, which I loaded in the “setup” chunk
in the RMarkdown document).</strong></p>
<p><strong>Next, look at the outgoing heat flux at the top of the atmosphere (70 km)
(I<sub>out</sub>) reported by the MODTRAN model. Is it greater or less than the heat
flux that you calculated was emitted by the ground?</strong></p></li>
<li><p><strong>Use the outgoing heat flux at the top of the atmosphere (I<sub>out</sub>) to
calculate the skin temperature (use the equation
<span class="math inline">\(I_{\text{out}} = \varepsilon \sigma T_{\text{skin}}^4)\)</span>).
What is the skin temperature, and how does it compare to the ground
temperature and the temperature at the tropopause, as reported by the
MODTRAN model (<code>t_tropo</code>)?</strong></p>
<p><strong>Assuming an environmental lapse rate of 6K/km, and using the
skin temperature that you calculated above, and the ground temperature
from the model, what altitude would you expect the skin height to be?</strong></p></li>
<li><p><strong>Double the CO<sub>2</sub> concentration and run MODTRAN again. Do not adjust the
ground temperature. Repeat the calculations from (b) of the skin
temperature and the estimated skin height.</strong></p>
<p><strong>What is the new skin temperature? What is the new skin height?</strong></p></li>
<li><p><strong>Put the CO<sub>2</sub> back to today’s value, but add cirrus clouds, using the
“standard cirrus” value for the clouds. Repeat the calculations from (b) of
the skin temperature and the skin height.</strong></p>
<p><strong>What is the new skin temperature? What is the new skin height?
Did the clouds or the doubled CO<sub>2</sub> have a greater effect on the
skin height?</strong></p></li>
</ol>
</div>
</div>
