---
title: Introduction to EES 3310/5310 Labs
author: Jonathan Gilligan
lab_number: 1
lab_date: '2021-01-25'
pubdate: '2020-12-31'
date: '2021-01-25'
pdf_url: /files/lab_docs/lab_01/lab_01_overview.pdf
slug: lab_01_overview
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: yes
---
# Overview of EES 3310/5310 Labs

The laboratories in this course are computational. My goals for the laboratory section are:

1. Learn about best practices for _reproducible research_ and get experience applying tools and methods for making 
   sure that your research is reliable, reproducible, and trustworthy.
   We will focus on research about climate science and climate and energy policy, but the methods and tools we will
   use are widely used in all kinds of research in natural and social sciences and also in the private sector.
2. Get experience working with real data: download and analyze data and report the results of your analysis.
3. Get experience working with computer models of different aspects of the climate system. Learn how to use models
   to do science, how to analyze and interpret the results of model simulations, and how to write reports about
   research using computational models.

## General Policies

* There will be **two** web resources for each lab: 
    * **Documentation** that describes the lab and tells you what you need to do to prepare and what you will do in the 
      lab class.
    * **An assignment** that provides a template you will use in carrying out the lab and writing it up. The assignment
      will consist of a web link for you to click on to accept the assignment in GitHub Classroom. After you accept
      the assignment, GitHub Classroom will copy the assignment into your own GitHub Classroom account.
      You will then clone the assignment from GitHub to your own computer or a computer in the lab classroom to work
      on it.

    Both the documentation and the assignment will be posted to the course web site at 
    <https://ees3310.jgilligan.org/schedule/> at least one week before the lab class.
* **Before** coming to lab:
    * Be sure to read the documentation for that week's lab.
    * Accept the assignment on GitHub Classroom (click on the Assignment link in the course web site). If you will be
      bringing your own computer to the lab, you may want to clone the assignment onto your own computer before you
      come to lab, but that's not strictly necessary. If you will be using one of the computers in the lab classroom,
      you can clone the assignment when you log in at the beginning of class.
      
* In the first lab, on January 25, Mr. de Wet will explain all of the different software we will be using and will
  walk you through all the steps of using Git to work with your assignments.
   
## Schedule for the Semester

The semester is divided roughly in half. 

### First Half of the Semester:

In the first half, the readings, class sessions, and laboratories will focus 
on understanding the science of how the earth's climate system works and how human perturbations to the environment may
affect the climate. 

The weekly labs during the first half of the semester will initiially focus on exercises from the book 
_Global Warming: Understanding the Forecast_ 
and then from March 15-28 you will work on using the reproducible research methods to write up a polished
report from one of the previous labs, and this report will be due before you come to lab on March 29.

### Second Half of the Semester

Starting on March 29, you will shift gears and apply the tools you have learned to analyzing policy. 
Specifically, you will analyze data on the economies and energy use of different countries around
the world and use these to compare different policy options for reducing greenhouse gas emissions. 
The labs will begin with exercises that follow the analyses you will be reading about in the book, _The Climate Fix_, and then 
you will perform a detailed analysis of policy options for a country of your choice to make a transition
to a cleaner energy supply.

You will write up a formal report on the country you choose, which will be due on May 1. The last two lab sessions on Apri. 19 and 26 
will be informal times for you to work on this report and ask questions from Prof. Gilligan and Mr. de Wet.

# Online Laboratory

In previous semesters, the lab met in a computer classroom in Stevenson Center or Wilson Hall. However, it is impossible to maintain 
safe distancing in those classrooms during the COVID pandemic, so the lab will be online. We will hold a synchronous lab session on 
Monday afternoons from 2:10--5:00, via Zoom. The links are posted on Brightspace. 

We will also record the lab sessions so that you can watch them asynchronously, and all the instructions for the labs are posted to the
course web site at <https://ees3310.jgilligan.org>.

You will need a computer for the labs. All of the software we will be using is free and open source, and it runs on Windows, MacOS, and Linux,
so no matter what kind of computer you have, you will be able to do the lab work.

# Software Tools

We will use four principal software tools for this class. All four are free and available for Windows, MacOS, and 
Linux. Detailed instructions for downloading and installing them are available on the course web site at
<https://ees3310.jgilligan.org/tools/>:

1. R: statistical analysis software (be sure to get the latest version, 4.0.3)
2. RStudio: a user-friendly interface to R, which makes it much easier to use (be sure to get the latest version, 1.4)
3. Git: a tool for keeping track of revisions in computer code and documents and coordinating working together with
   other people on a project.
