---
title: Preparation for Lab on Regulating Greenhouse Gas Emissions
lab_number: 12
lab_date: '2020-04-06'
pubdate: '2019-12-31'
date: '2020-04-06'
pdf_url: /files/lab_docs/regulation_lab/preparation_for_regulation_lab.pdf
slug: lab_12_preparation
fontsize: 12pt
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: yes
  pdf_document:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
    toc: yes
    includes:
      in_header: ees3310.sty
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(lubridate)
# library(xtable)
library(knitr)
library(kableExtra)

game_day = ymd("2020-04-06")
long_game_day = format(game_day, "%A %B %e")
short_game_day = format(game_day, "%b.\ %e")

```
## Overview

We will have an optional activity that will allow you to role-play different 
kinds of greenhouse gas emissions regulations. If you are interested, you may 
create a group of 4 and conduct this activity together (and post your results 
and what you learned on Piazza!). 

This exercise is completely optional. If you do it, it will help you understand
how the different methods of regulating emissions work, but if you already 
have too many obligations, you can skip it with no penalty.
Nothing from this exercise will be on the final exam.

We will introduce the exercise in lab on Monday and you will play it over the 
course of the week and we will review it in lab next Monday.

Your group will role-play the following regulations: 

* "**Command-and-Control**," in which the EPA mandates the maximum emissions for 
  each company,
* "**Cap and Trade**," in which the EPA mandates the total emissions, and gives 
  each company a certain number of permits, but the companies can buy and sell 
  permits,
* "**Emissions Tax**," in which the EPA imposes a tax on each ton of emissions, 
  and then reduces other taxes to keep the total government revenue constant.

Students will play different roles: some will act as government regulators at 
the Environmental Protection Agency and others will act as managers of different 
companies that must balance their desire to make money against the environmental 
damage from the pollution they emit.

To simplify things, we'll do the emissions-trading game with a zero-emissions 
baseline that will allow us to calculate costs and benefits of 
emitting CO~2~. 
In this case, the costs to the players will be the cost of buying permits to 
emit CO~2~ and the benefits will be the profits they earn. The costs to 
society will be the social cost of carbon (the damage caused by global warming) 
and the benefit will be the combination of profit earned by the companies (this 
benefits the companies, but it's also part of the gross domestic product of the 
nation) and money received from the players as taxes or payment for emissions 
permits.

## The Players

As mentioned, you will need a group of four students for this game. You can 
decide which role each member will have. 

1. One group member will play The Environmental Protections Agency (EPA) and 
   will decide how much to reduce pollution, how many permits to issue, or how 
   much to charge as a pollution tax.

   The EPA's motivation is to produce the best net benefit for society by 
   balancing the costs of reducing greenhouse gas emissions against the benefits 
   of limiting global warming.
2. A second group member will play Alpha Electricity: a large power company with 
   a varied portfolio of generating plants including coal, natural gas, and 
   nuclear.
   
   Alpha's motives are purely to produce the greatest profit for its 
   shareholders regardless of the cost to society of greenhouse gas emissions.
3. A third group member will play Beta Industries: a large heavy-industrial 
   conglomerate with many large factories producing steel, aluminum, and 
   petrochemicals such as plastics, paints, and pharmaceuticals.
   
   Beta's motives are purely to produce the greatest profit for its shareholders 
   regardless of the cost to society of greenhouse gas emissions.
4. The fourth group member will have the important role of facilitator. 

   This member will check in with each of the other players and keep track of 
   the success of each regulation. 

For the purposes of this exercise, we will assume that the EPA can accurately 
estimate the damage that would be caused by global warming, and thus, that it 
can also accurately estimate the social benefit of reducing greenhouse gas 
emissions. However, the EPA cannot accurately assess the costs individual 
companies will incur when they reduce their emissions. This means that the 
EPA's estimates of net benefits (benefits minus costs) is limited by its 
uncertainty about the cost of reducing emissions.

Only the EPA will know the social cost of greenhouse gas emissions, only Alpha 
will know Alpha's cost for reducing emissions, and only Beta will know Beta's 
cost for reducing emissions.

Without regulation, Alpha and Beta would each emit 
**150 million tons of CO~2~** per year. 

To keep things simple, emissions cuts will be figured in blocks of 10 million 
tons, so a firm can cut emissions by 
zero, 10 million tons, 20 million tons, ..., up to a maximum of 150 million tons 
(cutting emissions by 150 million tons means the firm reduces its emissions to 
zero).

## The Game

The game will have six stages. In these stages the students playing the part of 
the EPA will communicate with the students playing the parts of the different 
companies and the companies will communicate with each other. These 
communications should be private because if you are one of the companies, you 
don't want your competitors to learn about your plans.

You can communicate by email, Zoom, phone, text messaging or whatever method is 
convenient. You do not need to turn in the content of these communications, but 
each player should note the result of the communications (for instance the EPA 
should record the answers to its questions about marginal profits and the 
companies should record the number of permits they buy or sell and the price.

1. The EPA will gather information on the cost of abating pollution. 

   The EPA can ask four questions about each company's costs (I recommend 
   asking questions about the marginal profit at different amounts of emission). 
   Each company will answer the question. The companies may answer 
   strategically, meaning they may exaggerate the costs. The EPA may take this 
   into account in deciding how to use the answers to estimate the true cost of 
   reducing emissions.

2. The EPA will determine three possible courses of action:
   a. A command and control regulation, which mandates a specific emissions 
      reduction. Because the Constitution guarantees equality before the law, 
      this regulation must impose the same emissions cut for each firm.
   b. A cap-and-trade. Under this program, the total emissions cuts would be 
      the same and the EPA will issue permits to emit CO~2~. Each permit 
      will allow the owner to emit 10 tons of CO~2~. Total CO~2~ 
      emissions are 300 million tons minus the emissions cuts the EPA wants to 
      impose. 

      If the EPA wants to cut emissions by 200 million tons, it would issue 
      10 permits 
      ($300~\text{million} - 20 \times 10~\text{million} = 100~\text{million}$; 
      Each permit allows 10 million tons of emissions so
      $100~\text{million} / 10~\text{million} = 10~\text{permits}$). 

      To keep things simple, make the number of permits a multiple of 2. 
      The EPA will give each company an equal number of permits (if the EPA 
      issues 10 permits, it gives 5 to each company).
   c.	An emissions-tax program. Under this program, the EPA determines the tax 
      a firm must pay for every million tons of CO~2~ it emits. The firms 
      will then decide on their own how much to cut their emissions.

3. The firms determine how much CO~2~ they will emit under the 
   command-and-control program (this is easy). At the end of this round, the 
   EPA will publish the total benefit to society of the emissions reduction, 
   the firms will calculate their total costs (but keep this secret from the 
   EPA), and the facilitator will announce the total deadweight loss due to 
   inefficiencies in the regulation.

4. Permits will be distributed. An equal number of permits will be given to 
   each firm, and the firms may trade permits with each other. After the 
   permits are allocated, the facilitator will again announce the total 
   benefits to society and the deadweight loss.

5. An emissions tax will be imposed, at the price set by the EPA. The two firms 
   will be free to cut emissions by as much or as little as they want (between 
   0 and 150 million tons each). After each firm determines its final 
   emissions, the facilitator will once again announce the total benefits to 
   society and the deadweight loss.

6. Finally, each party should reveal the details used to make decisions at each 
   step, including the private information each firm has about its costs. 
   Consider the strengths and limitations of each regulatory program. Feel free 
   to share your results and insights on Piazza! 

## Acknowledgements

This exercise was adapted from The Pollution Game, an interactive exercise 
developed by Jay R. Corrigan, Associate Professor of Economics, Kenyon College.  
See J.R. Corrigan, ``The Pollution Game: A Classroom Exercise Demonstrating the 
Relative Effectiveness of Emissions Taxes and Tradable Permits,'' 
_The Journal of Economic Education_ **42**, 70--78 (2011) 
[doi: 10.1080/00220485.2011.536491](https://doi.org/10.1080/00220485.2011.536491)

